spring:
  application:
    name: gateway-web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        #唯一标识符
        - id: changgou_goods_route
          #用户请求需要路由到该服务[指定要路由的服务]
          uri: http://localhost:18081
          #路由规则配置
          predicates:
            #用户请求的域名规则配置
            #- Host=www.changgou.com**
            - Path:/brand/**
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true